### ISSUE TITLE
Walking into archives fails when a filename has spaces or other special characters

### ISSUE THREAD

**Issue by stefanofornari** [stefanofornari/vfs2nio#2]
Exception in thread "main" java.lang.IllegalArgumentException: Illegal character in opaque part at index 73: vfs:tar:file:///opt/uzz/gitminer/foo/vim.tar!/.vim/after/ftplugin/movable type_snippets.vim
	at java.base/java.net.URI.create(URI.java:903)
	at com.sshtools.vfs2nio.Vfs2NioPath.toUri(Vfs2NioPath.java:316)
	at ste.uzz.FilesMiner$FilesMinerVisitor.lambda$visitFile$3(FilesMiner.java:361)
	at [ste.uzz.logging.LazyLogger.info](http://ste.uzz.logging.lazylogger.info/)(LazyLogger.java:34)
	at ste.uzz.FilesMiner$FilesMinerVisitor.visitFile(FilesMiner.java:355)
	at ste.uzz.FilesMiner$FilesMinerVisitor.visitFile(FilesMiner.java:303)
	at ste.vfs2nio.tools.FileSystemTreeWalker.visit(FileSystemTreeWalker.java:232)
	at ste.vfs2nio.tools.FileSystemTreeWalker.walk(FileSystemTreeWalker.java:297)
	at ste.uzz.FilesMiner.launch(FilesMiner.java:129)
	at ste.uzz.FilesMiner.main(FilesMiner.java:158)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 73: vfs:tar:file:///opt/uzz/gitminer/foo/vim.tar!/.vim/after/ftplugin/movable type_snippets.vim
	at java.base/java.net.URI$Parser.fail(URI.java:2970)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3141)
	at java.base/java.net.URI$Parser.parse(URI.java:3177)
	at java.base/java.net.URI.<init>(URI.java:620)
	at java.base/java.net.URI.create(URI.java:901)
	... 9 more

**Comment by stefanofornari** [comment]
fixed in v0.11.3

**Comment by stefanofornari** [comment]
another fix in v0.11.5
