### ISSUE TITLE
Walking into archives fails with nested archives

### ISSUE THREAD

**Issue by stefanofornari** [stefanofornari/vfs2nio#3]
[vfs:gz:jar:file:///opt/uzz/gitminer/warbler/lib/jruby-complete-1.1.3.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.1/doc/rake.1.gz

Exception in thread "main" java.lang.IllegalStateException: org.apache.commons.vfs2.FileSystemException: Invalid descendent file name "./".
        at com.sshtools.vfs2nio.Vfs2NioDirectoryStream.iterator(Vfs2NioDirectoryStream.java:102)
        at ste.vfs2nio.tools.FileSystemTreeWalker$DirectoryNode.iterator(FileSystemTreeWalker.java:136)
        at ste.vfs2nio.tools.FileSystemTreeWalker.walk(FileSystemTreeWalker.java:291)
        at ste.uzz.FilesMiner.launch(FilesMiner.java:129)
        at ste.uzz.FilesMiner.main(FilesMiner.java:158)
Caused by: org.apache.commons.vfs2.FileSystemException: Invalid descendent file name "./".
        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveName(DefaultFileSystemManager.java:928)
        at org.apache.commons.vfs2.provider.AbstractFileObject.getChildren(AbstractFileObject.java:1117)
        at com.sshtools.vfs2nio.Vfs2NioDirectoryStream.iterator(Vfs2NioDirectoryStream.java:73)
        ... 4 more

**Comment by stefanofornari** [comment]
fixed in v0.11.4
